In [1]:
# Imports

import math
import numpy as np
from matplotlib import pyplot as plt
from numpy import random as rnd
import warnings,datetime,os,calendar,csv,time

import tensorflow as tf
import pandas as pd
import seaborn as sns

from keras.models import Model,Sequential
from keras.layers import Dense,LSTM,Conv2D,Dropout,BatchNormalization,Input,Concatenate,Add,Activation,MaxPooling2D,AveragePooling2D
import keras.backend as K

from sklearn import preprocessing as pp

from sklearn.cluster import KMeans,MeanShift
from sklearn.dummy import DummyClassifier,DummyRegressor
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,RandomForestClassifier,RandomForestRegressor
from sklearn.linear_model import BayesianRidge,Lasso,LinearRegression,SGDClassifier,SGDRegressor
from sklearn.mixture import BayesianGaussianMixture,GaussianMixture
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor,RadiusNeighborsClassifier,RadiusNeighborsRegressor,NearestNeighbors
from sklearn.manifold import Isomap,TSNE
from sklearn.model_selection import KFold,StratifiedKFold,train_test_split
from sklearn.svm import LinearSVC,LinearSVR
from sklearn.neural_network import BernoulliRBM,MLPClassifier,MLPRegressor
from sklearn.decomposition import FactorAnalysis,KernelPCA,PCA,MiniBatchSparsePCA,FastICA
from sklearn.preprocessing import CategoricalEncoder,KBinsDiscretizer,LabelEncoder,MinMaxScaler,OneHotEncoder,StandardScaler

from xgboost import XGBClassifier,XGBRegressor

import gym
import pygame
from pygame.locals import *

import pickle,h5py,json

import pandas_datareader as pdr
import urllib
from bs4 import BeautifulSoup
import iexfinance as iex
from iexfinance.stocks import get_historical_data
from scipy.signal import resample

warnings.filterwarnings('ignore')
sns.set()
plt.xkcd()

C:\Users\Jan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html

In [2]:
start_date = datetime.datetime(2014,1,1)
end_date = datetime.datetime(2017,1,1)

with open('Documents\stock_symb.txt','r') as f:
    lines = f.readlines()
content = [line.strip() for line in lines]
tickers = [content[i] for i in list(np.random.permutation(np.arange(len(content))))]

In [30]:
ticker_set = tickers[:15]

DATA = []
DF = []

ctr = 0
for ticker in ticker_set:

    print('Processing %d/%d'%(ctr,len(ticker_set)))
    ctr += 1
    try:
        df = get_historical_data(ticker,start=start_date,end=end_date,output_format='pandas')
    except:
        continue
    
    open_price = df['open'].values.reshape(1,-1)
    high_price = df['high'].values.reshape(1,-1)
    low_price = df['low'].values.reshape(1,-1)
    close_price = df['close'].values.reshape(1,-1)
    volume = df['volume'].values.reshape(1,-1)
    
    if open_price.shape[1]==0: continue
    if high_price.shape[1]==0: continue
    if low_price.shape[1]==0: continue
    if close_price.shape[1]==0: continue
    if volume.shape[1]==0: continue
    if any([math.isnan(float(k)) for k in list(open_price[0])]): continue
    if any([math.isnan(float(k)) for k in list(high_price[0])]): continue
    if any([math.isnan(float(k)) for k in list(low_price[0])]): continue
    if any([math.isnan(float(k)) for k in list(close_price[0])]): continue
    if any([math.isnan(float(k)) for k in list(volume[0])]): continue
    
    DF.append(df)
    
    ts = np.append(open_price,high_price,axis=0)
    ts = np.append(ts,low_price,axis=0)
    ts = np.append(ts,close_price,axis=0)
    ts = np.append(ts,volume,axis=0)
    
    DATA.append(ts)

Processing 0/15
Processing 1/15
Processing 2/15
Processing 3/15
Processing 4/15
Processing 5/15
Processing 6/15
Processing 7/15
Processing 8/15
Processing 9/15
Processing 10/15
Processing 11/15
Processing 12/15
Processing 13/15
Processing 14/15

In [29]:
DF[0]

               open     high      low    close  volume
date
2014-04-16  15.8897  16.2405  15.6968  15.7933   23690
2014-04-17  15.6880  16.4597  15.4425  16.4334   20249
2014-04-21  16.3896  16.6702  16.3896  16.6176   13690
2014-04-22  16.5649  16.6176  16.3106  16.5036   22988
2014-04-23  16.3808  16.6614  16.2931  16.5036   22551
2014-04-24  16.6526  16.6526  16.2317  16.3808   12533
2014-04-25  16.3106  16.4597  16.2580  16.3194   34586
2014-04-28  16.3457  16.4422  15.9336  16.2931   11565
2014-04-29  16.4071  16.4422  16.0651  16.1966   16806
2014-04-30  16.1177  16.1265  15.6705  15.8283   18324
2014-05-01  15.7670  15.9415  15.5828  15.7845   30275
2014-05-02  15.8634  15.8897  15.5740  15.7319   20044
2014-05-05  15.7056  15.7406  15.5916  15.6617   22647
2014-05-06  15.6354  15.6880  15.3548  15.4688   25814
2014-05-07  15.5653  15.5653  15.1268  15.3811   86048
2014-05-08  15.3811  15.5477  15.2583  15.3110   22372
2014-05-09  15.2320  16.2142  15.1706  16.0651   28561
2014-05-12  16.1879  16.5737  16.1440  16.3457   34440
2014-05-13  16.3720  16.3720  15.5039  15.5039   30823
2014-05-14  15.4513  15.5433  15.1706  15.1706   62009
2014-05-15  15.1268  15.2544  15.0479  15.1794   35555
2014-05-16  15.1356  15.3373  15.0830  15.3110   41571
2014-05-19  15.2864  15.3110  15.1268  15.1706   51330
2014-05-20  15.1706  15.4995  15.0216  15.3197   58898
2014-05-21  15.3197  15.3965  15.1093  15.1794   37410
2014-05-22  15.2057  15.2934  15.1180  15.1443   30847
2014-05-23  15.1794  15.6530  15.1268  15.5916   25701
2014-05-27  15.8371  16.4246  15.8108  16.3983   32668
2014-05-28  16.2756  16.4597  16.1857  16.4246   14447
2014-05-29  16.3983  16.4597  16.3106  16.4509   31689
...             ...      ...      ...      ...     ...
2016-11-17  32.0545  32.6312  32.0305  32.2468   42168
2016-11-18  32.2468  32.9676  32.2468  32.7754   58856
2016-11-21  32.8235  33.1599  32.0545  32.3909   40609
2016-11-22  32.1987  32.7754  32.1987  32.5832   41617
2016-11-23  32.3429  33.2078  32.0065  32.6312   18702
2016-11-25  32.4870  32.8715  32.2948  32.6793   32652
2016-11-28  32.4390  32.8235  32.3429  32.6793   48010
2016-11-29  32.7754  33.2079  32.5351  32.6312   22015
2016-11-30  32.7754  32.9917  32.3429  32.4390   59299
2016-12-01  32.5351  33.5203  31.7662  31.9584   40733
2016-12-02  31.7662  31.7662  29.3152  31.1895   74168
2016-12-05  31.5740  32.3669  31.4298  32.1506   72314
2016-12-06  32.2468  33.1118  31.9104  32.9196   53480
2016-12-07  32.8715  33.8807  32.7754  33.5443   68579
2016-12-08  33.5443  34.6016  33.4963  34.6016  106877
2016-12-09  34.6016  36.0914  34.3132  35.8030  121215
2016-12-12  35.6108  36.0851  34.2171  34.8419  116253
2016-12-13  35.0822  35.1043  33.9768  34.1210   48758
2016-12-14  34.1210  34.4574  33.8807  34.1210   32547
2016-12-15  34.0730  34.3132  33.9288  34.1210   61665
2016-12-16  34.3132  34.9861  34.0249  34.0730   83847
2016-12-19  34.2652  34.7458  33.8327  34.5535   56892
2016-12-20  34.7938  35.7069  34.6496  35.5147   51666
2016-12-21  35.3225  35.6108  34.9861  35.4666   49147
2016-12-22  35.5627  35.7069  34.8419  35.3225   32283
2016-12-23  35.4186  35.5147  34.7217  34.9861   24182
2016-12-27  34.8899  36.0433  34.8899  35.7069   23788
2016-12-28  35.8030  36.0914  35.4186  35.9472   39393
2016-12-29  35.9761  36.4095  35.8316  36.3614   26486
2016-12-30  36.3614  36.3614  35.5427  35.7835   26867

[684 rows x 5 columns]